backend/urls.py
from rest_framework import routers
from backend.api import ProductView, ServiceView, CerificateView


router = routers.DefaultRouter()
router.register('products', ProductView, 'products')
router.register('service', ServiceView, 'service')
router.register('certificate', CerificateView, 'certificate')

urlpatterns = router.urls

solarpv/urls.py
from django.urls import path
from django.shortcuts import redirect
from solarpv import views

app_name = 'solarpv'

urlpatterns = [
    path('', views.main, name="main"),
    path('register/', views.register, name="register"),
    path('login/', views.login_view, name="login"),
    path('module/', views.module, name="module"),
    path('performance/', views.performance, name="performance"),
    path('analytics/', views.analytics, name="analytics"),
    path('faq/', views.faq, name="faq"),
    path('client/', views.client, name="client"),
    path('location/', views.location, name="location"),
    path('product/', views.product, name="product"),
    path('test-standard/', views.test_standard, name="test-standard"),
    path('certificate/', views.certificate, name="certificate"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('main/', lambda request: redirect('/', permanent=False)),
]

solarpv_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('solarpv.urls')),
    path('api/', include('backend.urls'))
]

solarpv/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
    client_ID = models.CharField(max_length=10, unique=True)
    client_name = models.CharField(max_length=40)
    client_type = models.CharField(max_length=50)
    def __str__(self):
        return self.client_name

class TestStandard(models.Model):
    standard_ID = models.CharField(max_length=10, unique=True)
    standard_name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    published_date = models.CharField(max_length=50)
    
class User(models.Model):
    userID = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    job_title = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    office_phone = models.CharField(max_length=50, blank=True, null=True)
    cell_phone = models.CharField(max_length=50, null=True, blank=True)
    client_ID = models.ForeignKey(Client, to_field='client_ID', on_delete=models.CASCADE)

class Location(models.Model):
    location_ID = models.CharField(max_length=10, unique=True)
    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    fax_number = models.CharField(max_length=50)
    client_ID = models.ForeignKey(Client, to_field='client_ID', on_delete=models.CASCADE)

class Product(models.Model):
    model_number = models.CharField(max_length=50, unique=True)
    product_name = models.CharField(max_length=50)

class Certificate(models.Model):
    certificate_number = models.ForeignKey(Product, to_field='model_number', on_delete=models.CASCADE)
    report_number = models.CharField(max_length=50)
    issue_date = models.DateField()
    standard_ID = models.ForeignKey(TestStandard, to_field='standard_ID', on_delete=models.CASCADE)
    location_ID = models.ForeignKey(Location, to_field='location_ID', on_delete=models.CASCADE)
    model_number = models.CharField(max_length=50)

solarpv/forms.py
from django import forms
from .models import User, Certificate, Location, Client, Product, TestStandard

class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ['client_ID', 'client_name', 'client_type']

solarpv/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

# Create your views here.
from django.urls import reverse
from solarpv.models import User, Client
from solarpv.forms import ClientForm


def main(request):
    return render(request, 'solarpv/main.html')

def register(request):
    client_name = Client.objects.all()
    if request.method == "POST":
        company = request.POST['company']
        client = Client.objects.get(client_ID=company)
        reg_form = User.objects.create(userID=request.POST['username'], client_ID=client)
        reg_form.password = request.POST['password']
        reg_form.first_name = request.POST['first']
        reg_form.middle_name = request.POST['middle']
        reg_form.last_name = request.POST['last']
        reg_form.cell_phone = request.POST['cell_phone']
        reg_form.job_title = request.POST['job_title']
        reg_form.email = request.POST['email']
        reg_form.office_phone = request.POST['office_phone']
        reg_form.client_ID = client
        reg_form.save()
        return HttpResponse('Success')


    return render(request, 'solarpv/register.html', {'client_name':client_name})

def login_view(request):
    error = ""
    if request.method == "POST":
        username = request.POST['userid']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.is_superuser:
                return redirect("/admin/")
            elif user.is_staff:
                return redirect("/")
            else:
                error = "Error, User found, but not a staff"
        else:
            error = "Error, User not found"
    return render(request, 'solarpv/login.html', {'error':error})

def faq(request):
    return render(request, 'solarpv/faq.html')

def performance(request):
    return render(request, 'solarpv/performance.html')

def module(request):
    return render(request, 'solarpv/module.html')

def analytics(request):
    return render(request, 'solarpv/analytics.html')

def client(request):

    if request.method != 'POST':
        form = ClientForm()
    else:
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('solarpv:dashboard'))
    context = {'form': form}
    return render(request, 'solarpv/client.html', context)


def location(request):
    return render(request, 'solarpv/location.html')

def product(request):
    return render(request, 'solarpv/product.html')

def test_standard(request):
    return render(request, 'solarpv/test-standard.html')

def certificate(request):
    return render(request, 'solarpv/certificate.html')

def dashboard(request):
    return render(request, 'solarpv/dashboard.html')

solarpv/templates/solarpv/analytics.html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="theme-color" content="#5d4037">
  <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/solarpv/css/materialize.css"  media="screen,projection"/>

      <link type="text/css" rel="stylesheet" href="/static/solarpv/css/style.css"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	  
	  <title>analytics</title>
  </head>

  <body>
    <header id="head">

      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="/static/solarpv/js/materialize.js"></script>
	  <!--<script type="text/javascript" src="js/main.js"></script>-->
	  
	  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
	  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
	  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
	  <script type="text/babel" src="/static/solarpv/js/layout.js"></script>
	  <script type="text/babel" src="/static/solarpv/js/tabs.js"></script>
	  

    </header>


    <main class="brown darken-2">
      
	    <div class="row">
			<div>
				<div id="sideBarL" class="col l3 left">
				  <script type="text/javascript" src="/static/solarpv/js/location.js"></script>
				</div>
				<div class="col l6">
				  <div class="card white hoverable">
					<div class="card-content">
						<div id="mlp" class="section">
							<h5>Module Lifetime Prediction</h5>
						</div>
						<div>
							<img src="/static/solarpv/images/energy.png" width="540" height="280">
						</div>
						<div>
							<p class="section">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
								Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
							</p>
						</div>
						<div class="divider"></div>
						<div id="ene" class="section">
							<h5>Energy Prediction</h5>
						</div>
						<div>
							<img src="/static/solarpv/images/light.jpg" width="560" height="280">
						</div>
						<div>
							<p class="section">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
							</p>
						</div>
					</div>
				  </div>
				</div>
				<div id="sideBarR" class="col l3"></div>
			</div>
		</div>
        
		
	  
	  
    </main>

    <footer id="foot" class="page-footer brown darken-3"></footer>

  </body>
</html>

solarpv/templates/solarpv/certificate.html
<h1>certificate</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>

solarpv/templates/solarpv/dashboard.html
<h1>dashboard</h1>
<a href="{% url 'solarpv:client' %}"><button>client</button></a>
<a href="{% url 'solarpv:location' %}"><button>location</button></a>
<a href="{% url 'solarpv:product' %}"><button>product</button></a>
<a href="{% url 'solarpv:test-standard' %}"><button>test-standard</button></a>
<a href="{% url 'solarpv:certificate' %}"><button>certificate</button></a>

solarpv/templates/solarpv/faq.html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="theme-color" content="#5d4037">
  <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>

      <link type="text/css" rel="stylesheet" href="/static/css/style.css"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

	  <title>faq</title>
  </head>

  <body>
    <header id="head">

      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="/static/js/materialize.js"></script>
	  <!--<script type="text/javascript" src="js/main.js"></script>-->

	  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
	  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
	  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
	  <script type="text/babel" src="/static/js/layout.js"></script>



    </header>


    <main class="brown darken-2">

	    <div class="row">
			<div>
				<div id="sideBarL" class="col l3 left">
				  <script type="text/javascript" src="/static/js/location.js"></script>
				</div>
				<div class="col l6">
				  <div class="card white hoverable">
					<div class="card-content">
						<div id="about" class="section center-align">
							<h5>About Us</h5>
						</div>
						<div>
							<img src="/static/images/us.jpg" width="540" height="280">
						</div>
						<div>
							<p class="section">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
								Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
								Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
							</p>
						</div>
						<div class="divider"></div>
						<div id="contact" class="section center-align">
							<h5>Contact Us</h5>
						</div>
						<div>
							<p class="section">
								Leave us a message and a representative will reach out to you with in 24 hours!
							</p>
						</div>
						<div>
							<form action="mailing" autocomplete="off">
							  <div class="row">
								<div class="input-field col l9 center-align">
									<i class="material-icons prefix" style="font-size: 25px;">account_circle</i>
									<input type="text" name='name' class="validate" id="name">
									<label for="name" >Name</label>
								</div>
							  </div>
							  <div class="row">
								<div class="input-field col l9 offset-s1 center-align">
								  <i class="material-icons prefix" style="font-size: 25px;">email</i>
								  <input type="email" required name="email" class="validate">
								  <label for="email" data-error="Please enter valid email address">Email</label>
								</div>
							  </div>
							  <div class="row">
								<div class="input-field col l9 center-align">
									<i class="material-icons prefix" style="font-size: 25px;">phone</i>
									<input type="number" name='num' class="validate" id="num">
									<label for="num" data-error="Please enter valid 10 digit phone number">Phone</label>
								</div>
							  </div>
							  <div class="row">
								<div class="input-field col l11 center-align">
								  <i class="material-icons prefix" style="font-size: 25px;">create</i>
								  <textarea id="textarea1" class="materialize-textarea" data-length="200"></textarea>
								  <label for="textarea1">Leave a Message</label>
								</div>
							  </div>
							  <div class="row">
								<div class="col s12 l6 offset-l3 center-align">
									<button class="btn waves-effect waves-light amber darken-1" name="login" type="submit" value="Submit">Submit</button>
								</div>
							  </div>
							</form>
						</div>
					</div>
				  </div>
				</div>

				<div id="sideBarR" class="col l3"></div>
			</div>
		</div>




    </main>

    <footer id="foot" class="page-footer brown darken-3">

    </footer>

  </body>
</html>

solarpv/templates/solarpv/location.html
<h1>location</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>

solarpv/templates/solarpv/login.html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="theme-color" content="#5d4037">
  <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/solarpv/css/materialize.css"  media="screen,projection"/>

      <link type="text/css" rel="stylesheet" href="/static/solarpv/css/style.css"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <header>

      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="/static/solarpv/js/materialize.js"></script>
	  <!--<script type="text/javascript" src="js/main.js"></script>-->
	  <script type="text/javascript">
		( function($) {
			// we can now rely on $ within the safety of our "bodyguard" function
			$(document).ready( function() { 
				$('.slider').slider({
					indicators: false,
					transition: 1200,
					interval: 7000,
				});  
				} );
			$('.slider').slider();
		} ) ( jQuery );
	  </script>

      <!--Navigation Bar-->
      <nav class="nav-extended">
        <div class="nav-wrapper brown darken-3">
          <a href="/" class="brand-logo logo center hide-on-med-and-up">G&A Solar Research</a>
		  <a href="/" class="brand-logo hide-on-small-only">
		  <img style="padding-top: 4px; padding-left: 5px;" class="responsive-img" src="/static/solarpv/images/sun.png" height="50" width="50">
		  G&A Solar</a>
          <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
			<li><a href="/register"><i class="material-icons right">developer_board</i>Register</a></li>
            <li><a href="/login"><i class="material-icons right red-text">account_circle</i>Login</a></li>
            <li><a href="/faq"><i class="material-icons right">error_outline</i>About Us</a></li>
        </div>
		<div class="nav-content brown darken-3">
		  <ul class="tabs tabs-transparent hide-on-small-only">
		  </ul>
		</div>
      </nav>
	  

    </header>


    <main class="brown darken-2">
      
	  <div class="row section">
		  <div class="col l6 offset-l3 center-align hoverable" style="background-color: white;">
				<form action="" method="post" autocomplete="off" class="col l12 s12">{% csrf_token %}
					<div class="col s12 l12 center-align">
						<h5>Log In</h5>
                        <p>{{ error }}</p>
					</div>
				  <div class="row">
					<div class="input-field col s10 l6 offset-l3 offset-s1 center-align">
					  <input type="text" required name="userid" class="validate">
					  <label for="email" data-error="Please enter valid userID address">UserID</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col s10 l6 offset-l3 offset-s1 center-align">
						<input type="password" required autocomplete="off" class="validate" name="password">
						<label for="password">Password</label>
					</div>
				  </div>
				  <div class="row">
					<div class="col s12 l6 offset-l3 center-align">
						<button class="btn waves-effect waves-light" name="login">Login
						  <i class="material-icons right">code</i>
						</button>
					</div>
				  </div>
				  <div class="row">
					<div class="">
						<a href="forgot">Forgot Password?</a>
					</div>
				  </div>
				</form>
			</div>
		  </div>
	  </div>
	  
	  
    </main>

    <footer class="page-footer brown darken-3">
      <div class="container">
        <div class="row">
          <div class="col l12 s12 center-align">
            <p class="white-text">G & A Solar Research
			<br>
			7001 E Williams Field Rd, Mesa, AZ 85212
			<br>
			(480) 727-1585 | GASolar@ga.com
			<br>
			Site Map | Terms & Conditions | Privacy Policy | About Us
			</p>

          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2019 All rights reserved
        <a class="grey-text text-lighten-4 right" href="#">G&A Solar</a>
        </div>
      </div>
    </footer>

  </body>
</html>

solarpv/templates/solarpv/mailing.html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="theme-color" content="#5d4037">
  <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/css/materialize.css"  media="screen,projection"/>

      <link type="text/css" rel="stylesheet" href="/static/css/style.css"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	  
	  <meta http-equiv="refresh" content="3; URL='faq'" />
  </head>

  <body>
    <header>

      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="/static/js/materialize.js"></script>
	  <!--<script type="text/javascript" src="/static/js/main.js"></script>-->
	  
	  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
	  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
	  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
	  
	  

    </header>


    <main class="brown darken-2">
      
	    <div class="row">
			<div class="col l6 offset-l3 center-align">
				<div class="card white hoverable">
					<div class="card-content">
						<div id="about" class="section center-align">
							<h5>Thank you!</h5>
						</div>
						<div>
							<p class="section">
								Your feedback is very important to us. A representative will reach out to you soon!
							</p>
						</div>
						<div>
							<img src="/static/images/thank.jpg" width="540" height="280">
						</div>
					</div>
				
				</div>
			</div>
		</div>
        
		
	  
	  
    </main>

    <footer class="page-footer brown darken-3">
    </footer>

  </body>
</html>

solarpv/templates/solarpv/product.html
<h1>product</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>

solarpv/templates/solarpv/register.html
<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="theme-color" content="#5d4037">
  <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/solarpv/css/materialize.css"  media="screen,projection"/>

      <link type="text/css" rel="stylesheet" href="/static/solarpv/css/style.css"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <header>

      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script type="text/javascript" src="/static/solarpv/js/materialize.js"></script>
	  <!--<script type="text/javascript" src="js/main.js"></script>-->
	  <script type="text/javascript">
		( function($) {
			// we can now rely on $ within the safety of our "bodyguard" function
			$(document).ready( function() { 
				$('.slider').slider({
					indicators: false,
					transition: 1200,
					interval: 7000,
				});  
				} );
			$('.slider').slider();
		} ) ( jQuery );
	  </script>

      <!--Navigation Bar-->
      <nav class="nav-extended">
        <div class="nav-wrapper brown darken-3">
          <a href="/" class="brand-logo logo center hide-on-med-and-up">G&A Solar Research</a>
		  <a href="/" class="brand-logo hide-on-small-only">
		  <img style="padding-top: 4px; padding-left: 5px;" class="responsive-img" src="/static/solarpv/images/sun.png" height="50" width="50">
		  G&A Solar</a>
          <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
			<li><a href="/register"><i class="material-icons right blue-text">developer_board</i>Register</a></li>
            <li><a href="/login"><i class="material-icons right">account_circle</i>Login</a></li>
            <li><a href="/faq"><i class="material-icons right">error_outline</i>About Us</a></li>
        </div>
		<div class="nav-content brown darken-3">
		  <ul class="tabs tabs-transparent hide-on-small-only">
		  </ul>
		</div>
      </nav>

    </header>


    <main class="brown darken-2">
      
	  <div class="row section">
		  <div class="col l10  offset-l1 hoverable" style="background-color: white; padding-right: 3em;">
				<form action="{% url 'solarpv:register' %}" method="post" autocomplete="off" class="col l12 s12">
					{% csrf_token %}
				  <div class="row">
					<p id="subtit2">Create Account</p>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="text" required  name='username' class="validate" id="username" data-length="8">
						<label for="username" data-error="Username must be 8 characters long">Username</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col s10 l6 offset-l1 offset-s1 center-align">
						<input name="password" type="password" required autocomplete="off" class="validate" data-length="8">
						<label for="password" data-error="Password must be at most 8 characters long comprising at least a digit, a lowercase letter, and an uppercase letter">Password</label>
					</div>
				  </div>
				  <div class="row">
					<p id="subtit2">Personal Information</p>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="text" required name='first' class="validate" id="first">
						<label for="first" >First Name</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="text" name='middle' class="validate" id="middle">
						<label for="middle">Middle Name</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="text" required  name='last' class="validate" id="last">
						<label for="last" data-error="Last Name Required">Last Name</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="text" required name='job_title' class="validate" id="add1">
						<label for="add1" >Job Title</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="number" required name='office_phone' class="validate" id="phone">
						<label for="city" >Office Phone Number</label>
					</div>
				  </div>
				  <div class="row">
					<p id="subtit2">Contact Information</p>
				  </div>
				  <div class="row">
					<div class="input-field col s10 l6 offset-l1 offset-s1 center-align">
					  <input type="email" required name="email" class="validate">
					  <label for="email" data-error="Please enter valid email address">Email</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
						<input type="number" name='cell_phone' class="validate" id="num1">
						<label for="num1" >Phone</label>
					</div>
				  </div>
				  <div class="row">
					<div class="input-field col l6 offset-l1 center-align">
                        <select name="company">
                            <option value="">---------------------</option>
                            {% for client in client_name %}
                                <option value="{{ client.client_ID }}">{{ client.client_name }}</option>
                            {% endfor %}
                        </select>
						<label for="company">Company</label>
					</div>
				  </div>
				  <div class="row">
					<div class="col s12 l8 offset-l2 center-align">
						<button class="btn waves-effect waves-light red" name="login" type="submit" value="Submit">Register
						  <i class="material-icons right">code</i>
						</button>
					</div>
				  </div>
				  <div class="row">
					<p id="">By pressing "Register" you agree to the <a href="#">Terms & Conditions</a></p>
				  </div>
				</form>
			</div>
		  </div>
	  </div>
	  
	  
    </main>

    <footer class="page-footer brown darken-3">
      <div class="container">
        <div class="row">
          <div class="col l12 s12 center-align">
            <p class="white-text">G & A Solar Research
			<br>
			7001 E Williams Field Rd, Mesa, AZ 85212
			<br>
			(480) 727-1585 | GASolar@ga.com
			<br>
			Site Map | Terms & Conditions | Privacy Policy | About Us
			</p>

          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2019 All rights reserved
        <a class="grey-text text-lighten-4 right" href="#">G&A Solar</a>
        </div>
      </div>
    </footer>
    					<script>
						$(document).ready(function() {
							$('select').material_select();
						});
					</script>
  </body>
</html>

solarpv/templates/solarpv/test-standard.html
<h1>test-standard</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button>submit</button>
</form>